services:
  couchdb:
    expose:
      - 5984
    image: treehouses/rpi-couchdb:2.0.0
    ports:
      - "2200:5984"
      - "2201:5986"
  db-init:
    image: treehouses/planet:rpi-db-init-latest
    depends_on:
      - couchdb
  planet:
    image: treehouses/planet:rpi-latest
    ports:
      - "80:80"
    environment:
      - MULTIPLE_IPS=true
      - HOST_PROTOCOL=http
      - DB_HOST=127.0.0.1
      - DB_PORT=2200
    depends_on:
      - couchdb
version: "2"
