services:
  couchdb:
    expose:
      - 5984
    image: treehouses/couchdb:2.3.0
    ports:
      - "5984:5984"
      - "5986:5986"
  db-init:
    image: ${DOCKER_DB_INIT}
    depends_on:
      - couchdb
    environment:
      - COUCHDB_HOST=http://couchdb:5984
  planet:
    image: ${PLANET}
    ports:
      - "80:80"
    environment:
      - HOST_PROTOCOL=http
      - DB_HOST=127.0.0.1
      - DB_PORT=5984
    depends_on:
      - couchdb
version: "2"
